# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lance Parsons
name: Lance Parsons
email: lance@lanceparsons.com
description: >- # this means to ignore newlines until "baseurl:"
 Research Software Engineer, Bioinformatics Analyst, Home Brewer
# twitter_username: code_brewer
github_username: lparsons
minimal_mistakes_skin: dark # "air", "aqua", "contrast", "dark", "default", "dirt", "neon", "mint", "plum" "sunrise"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name     : "Lance Parsons"
  avatar   : "/assets/images/bio-photo.png"
  bio      : "Research Software Engineer, Bioinformatics Analyst, Home Brewer"
  location : "New Jersey, USA"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://lanceparsons.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lparsons"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      url: "https://bitbucket.org/lance_parsons"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/lparsons"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=PKiPYEwAAAAJ"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Lance_Parsons"
    - label: "ORCiD"
      icon: "fab fa-fw fa-orcid"
      url: "http://orcid.org/0000-0002-8521-714X"

footer:
  links:
      # - label: "Twitter"
      #   icon: "fab fa-fw fa-twitter-square"
      #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lparsons/lparsons.github.io"
      # - label: "Instagram"
      #   icon: "fab fa-fw fa-instagram"
      #   url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

